
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MasVidaWebMVC
{

using System;
    using System.Collections.Generic;
    
public partial class Audit
{

    public int AuditID { get; set; }

    public string AuditDescription { get; set; }

    public Nullable<int> UserID { get; set; }

    public Nullable<System.DateTime> AuditDateTime { get; set; }



    public virtual User User { get; set; }

}

}
