
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MasVidaWebMVC
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
public partial class Parameter
{

    public int ParameterID { get; set; }
        [Required]
    public string ParameterName { get; set; }

    public string ParameterValue { get; set; }

    public byte[] ParameterDescription { get; set; }

}

}
