
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MasVidaWebMVC
{

using System;
    using System.Collections.Generic;
    
public partial class Product
{

    public Product()
    {

        this.Transactions = new HashSet<Transaction>();

        this.Users = new HashSet<User>();

    }


    public int ProductID { get; set; }

    public string ProductName { get; set; }

    public string ProductDescription { get; set; }

    public double ProductPrice { get; set; }

    public bool IsActive { get; set; }



    public virtual ICollection<Transaction> Transactions { get; set; }

    public virtual ICollection<User> Users { get; set; }

}

}
