
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MasVidaWebMVC
{

using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;

    
public partial class Resource
{

    public Resource()
    {

        this.UserTypes_Resources = new HashSet<UserTypes_Resources>();

    }


    public int ControllerID { get; set; }
        [Required]
    public string ControllerName { get; set; }



    public virtual ICollection<UserTypes_Resources> UserTypes_Resources { get; set; }

}

}
