
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MasVidaWebMVC
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TransactionType
{

    public TransactionType()
    {

        this.Transactions = new HashSet<Transaction>();

    }


    public int TransactionTypeID { get; set; }
        [Required]
    public string TransactionTypeName { get; set; }

    public string TransactionTypeDescription { get; set; }



    public virtual ICollection<Transaction> Transactions { get; set; }

}

}
