
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MasVidaWebMVC
{
    using System;
    using System.ComponentModel.DataAnnotations;


    public partial class Transaction
{

    public int TransactionID { get; set; }

    public string ProductName { get; set; }

    public double ProductPrice { get; set; }

    public System.DateTime TransactionCreationDate { get; set; }

    public Nullable<System.DateTime> TransactionPaymentDate { get; set; }
        [Required]
    public bool IsPaid { get; set; }

    public int TransactionTypeID { get; set; }

    public int ProductID { get; set; }
        
    public int UserID { get; set; }



    public virtual Product Product { get; set; }

    public virtual TransactionType TransactionType { get; set; }

    public virtual User Users { get; set; }

}

}
