
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MasVidaWebMVC
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
public partial class UserType
{

    public UserType()
    {

        this.Users = new HashSet<User>();

        this.UserTypes_Resources = new HashSet<UserTypes_Resources>();

    }


    public int UserTypeID { get; set; }

    public string UserTypeName { get; set; }

    public string Description { get; set; }



    public virtual ICollection<User> Users { get; set; }

    public virtual ICollection<UserTypes_Resources> UserTypes_Resources { get; set; }

}

}
