
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MasVidaWebMVC
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class User
{

    public User()
    {

        this.Transactions = new HashSet<Transaction>();

        this.Audits = new HashSet<Audit>();

    }

        [Required]
    public int UserID { get; set; }
        [Required]
    public string Name { get; set; }
        [Required]
    public string LastName { get; set; }
        [Range(0,99999999,ErrorMessage ="Ingrese un DNI válido.")]
    public string DNI { get; set; }

    public string Address { get; set; }
        [DataType(DataType.EmailAddress)]
    public string Email { get; set; }
        [DataType(DataType.PhoneNumber)]
    public string Phone { get; set; }
        [DataType(DataType.Date)]
    public Nullable<System.DateTime> Birthday { get; set; }
    public string UserName { get; set; }
        [DataType(DataType.Password)]
    public string UserPassword { get; set; }

    public Nullable<int> ProductID { get; set; }
        [Required]
    public bool IsActive { get; set; }
        [Required]
    public int UserTypeID { get; set; }

    public Nullable<int> FamilyGroupID { get; set; }

    public Nullable<System.DateTime> CreationDateTime { get; set; }

    public Nullable<int> LastTransactionID { get; set; }
        [DataType(DataType.Currency)]
    public Nullable<double> AccountTotal { get; set; }



    public virtual FamilyGroup FamiliesGroup { get; set; }

    public virtual Product Product { get; set; }

    public virtual UserType UserType { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; }

    public virtual ICollection<Audit> Audits { get; set; }

}

}
